### ISSUE TITLE
Cmake-gui configure error 

### ISSUE THREAD

**Issue by Runasia** [East-Face/TEASER-plusplus-win#2]
Hi !
Thank you for your review.

I build a new folder name as "build1" and put
+ googletest-src
+ pmc-src
+ pybind11-src
+ spectra-src
+ tinyply-src
in it.
For the sake of safety, I put the last name contain "-build" of folders to "build1".
When i configure in cmake-gui and get  like this
`CMake Error at CMakeLists.txt:100 (add_subdirectory):
  The source directory

​    E:/xx/opmvgdate/TeaserWin/TEASER-plusplus-win/build1/pmc-src

  does not contain a CMakeLists.txt file.

CMake Error at CMakeLists.txt:109 (add_subdirectory):
  The source directory

​    E:/xx/opmvgdate/TeaserWin/TEASER-plusplus-win/build1/tinyply-src

  does not contain a CMakeLists.txt file.

CMake Error at CMakeLists.txt:111 (target_include_directories):
  Cannot specify include directories for target "tinyply" which is not built
  by this project.

CMake Error at CMakeLists.txt:157 (export):
  export given target "tinyply" which is not built by this project.`

Should I change Cmakelist.txt or something ?
Have a nice day :)

**Comment by East-Face** [comment]
sorry, I did not update the file. Later, I will update the file. You can try again

**Comment by East-Face** [comment]
I updated the readme file so you can follow the steps

**Comment by Runasia** [comment]
Thank you very much for your reply ！

I re clone code , and following steps  , unfortunately i get some error too .
I noticed if i make blank  CMakeLists.txt file in /pmc-src and /tinyply-src can reduce 2 error .
So i guess it miss some file ,  
![image-20240712155248667](https://github.com/user-attachments/assets/56ed25db-8073-4d29-80f0-16f4c850d78d)
and i find they has been update but can't click 
![image](https://github.com/user-attachments/assets/73f37d7f-8f9c-4cb7-94b4-a25b8dfab6d7)

I'm not sure about maybe vs vision(2022) or camke(3.30.0) vision or something .

Have a nice day! :-)

**Comment by East-Face** [comment]
Sorry, I have some problems with git. You can send me an email and I will send you the code by email

**Comment by Runasia** [comment]
> Sorry, I have some problems with git. You can send me an email and I will send you the code by email

Thank you . My email is runasia@foxmail.com

**Comment by TheKrzysiek108** [comment]
@Runasia I have the same problem, could you send me missing files to thekrzysiek108@gmail.com?

**Comment by TheKrzysiek108** [comment]
@East-Face same question, could you send me missing files to thekrzysiek108@gmail.com?

**Comment by Runasia** [comment]
this is file , and if you have problem , you can take issuses again ..
just like when use vs build problem&nbsp; like image-2024xx.png , add&nbsp;
if (MSVC)
&nbsp; &nbsp; # 添加 /bigobj 编译选项
&nbsp; &nbsp; set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /bigobj")
&nbsp; &nbsp; set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} /bigobj")
endif()
in cmakelist.txt&nbsp; can solve it ..&nbsp;




符文从物语
***@***.***



&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "East-Face/TEASER-plusplus-win"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年7月21日(星期天) 中午1:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [East-Face/TEASER-plusplus-win] Cmake-gui configure error  (Issue #2)





 
@East-Face same question, could you send me missing files to ***@***.***?
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: ***@***.***&gt;


从QQ邮箱发来的超大附件

TEASER-plusplus-win-master.7z (59.25M, 2024年08月22日 14:32 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=36663838cd6a2ecdd584a92c1762501e1c125c01020101014954080f024f5455065615010057061c52515b5c5700510401045d0a317f626521276b7d634f125d1115485444114f460d0815555011165416480f42315f&code=df881bb1

**Comment by East-Face** [comment]
？？？？？


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "East-Face/TEASER-plusplus-win"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年7月23日(星期二) 下午2:38
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [East-Face/TEASER-plusplus-win] Cmake-gui configure error  (Issue #2)





 this is file , and if you have problem , you can take issuses again .. 
 just like when use vs build problem&amp;nbsp; like image-2024xx.png , add&amp;nbsp; 
 if (MSVC) 
 &amp;nbsp; &amp;nbsp; # 添加 /bigobj 编译选项 
 &amp;nbsp; &amp;nbsp; set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /bigobj") 
 &amp;nbsp; &amp;nbsp; set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} /bigobj") 
 endif() 
 in cmakelist.txt&amp;nbsp; can solve it ..&amp;nbsp; 
 
 
 
 
 符文从物语 
 ***@***.*** 
 
 
 
 &amp;nbsp; 
 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "East-Face/TEASER-plusplus-win"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2024年7月21日(星期天) 中午1:29 
 ***@***.***&amp;gt;; 
 ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [East-Face/TEASER-plusplus-win] Cmake-gui configure error  (Issue #2) 
 
 
 
 
 
   
 @East-Face same question, could you send me missing files to ***@***.***? 
   
 — 
 Reply to this email directly, view it on GitHub, or unsubscribe. 
 You are receiving this because you were mentioned.Message ID: ***@***.***&amp;gt; 
 
 
 从QQ邮箱发来的超大附件 
 
 TEASER-plusplus-win-master.7z (59.25M, 2024年08月22日 14:32 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&amp;k=36663838cd6a2ecdd584a92c1762501e1c125c01020101014954080f024f5455065615010057061c52515b5c5700510401045d0a317f626521276b7d634f125d1115485444114f460d0815555011165416480f42315f&amp;code=df881bb1

**Comment by Runasia** [comment]
sorry！&nbsp;&nbsp;I' don't know what&nbsp; i did ...
Is a mistake and impolite&nbsp;...


send a cmakelist.txt code due to build in vs2022 has a samll troblem....

**Comment by changruizhu96** [comment]
Hi, I had the same issue. Could you please send me your code? zhuchangrui1996@outlook.com

**Comment by East-Face** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "East-Face/TEASER-plusplus-win"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2025年3月30日(星期天) 凌晨4:53
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [East-Face/TEASER-plusplus-win] Cmake-gui configure error  (Issue #2)



   
Hi, I had the same issue. Could you please send me your code? ***@***.***

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: ***@***.***&gt;
  changruizhu96 left a comment (East-Face/TEASER-plusplus-win#2)
 
Hi, I had the same issue. Could you please send me your code? ***@***.***
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: ***@***.***&gt;


从QQ邮箱发来的超大附件

TEASER-plusplus-win-master.7z (59.25M, 2025年04月30日 09:46 到期)进入下载页面：https://mail.qq.com/cgi-bin/ftnExs_download?k=60396566cf397bc432d5520c153105174a4d5c5f0102020d1f095d50561c050d565c480007015515510a575256570f00570a5353332c376c77783623611c4754474a150a46421a4f5b57480b5242435d4017521c330c&t=exs_ftn_download&code=29ef3178
